### ISSUE TITLE
Compiling errors:couldn't open auxiliary file,Natbib version - not for normal IEEE work

### ISSUE THREAD

**Issue by xiaoxstz** [fcyu/HKUST_PhD_MPhil_thesis_Latex#1]
When I build `thesis.tex`, it throws the errors below

> bibtex: security risk: running with elevated privileges
This is BibTeX, Version 0.99d (MiKTeX 21.12.10 Portable)
The top-level auxiliary file: ./output/thesis.aux
I couldn't open auxiliary file 1_title.aux
---line 19 of file ./output/thesis.aux
 : \@input{1_title.aux
 :                    }
I'm skipping whatever remains of this command
I couldn't open auxiliary file 2_authorization.aux
---line 21 of file ./output/thesis.aux
 : \@input{2_authorization.aux
 :                            }
I'm skipping whatever remains of this command
I couldn't open auxiliary file 3_signature.aux
---line 23 of file ./output/thesis.aux
 : \@input{3_signature.aux
 :                        }
I'm skipping whatever remains of this command
I couldn't open auxiliary file 4_dedicate.aux
---line 25 of file ./output/thesis.aux
 : \@input{4_dedicate.aux
 :                       }
I'm skipping whatever remains of this command
I couldn't open auxiliary file 5_acknowledgement.aux
---line 26 of file ./output/thesis.aux
 : \@input{5_acknowledgement.aux
 :                              }
I'm skipping whatever remains of this command
I couldn't open auxiliary file abstract.aux
---line 31 of file ./output/thesis.aux
 : \@input{abstract.aux
 :                     }
I'm skipping whatever remains of this command
I couldn't open auxiliary file chapter1.aux
---line 33 of file ./output/thesis.aux
 : \@input{chapter1.aux
 :                     }
I'm skipping whatever remains of this command
I couldn't open auxiliary file chapter2.aux
---line 35 of file ./output/thesis.aux
 : \@input{chapter2.aux
 :                     }
I'm skipping whatever remains of this command
I couldn't open auxiliary file chapter3.aux
---line 36 of file ./output/thesis.aux
 : \@input{chapter3.aux
 :                     }
I'm skipping whatever remains of this command
I couldn't open auxiliary file chapter4.aux
---line 37 of file ./output/thesis.aux
 : \@input{chapter4.aux
 :                     }
I'm skipping whatever remains of this command
I couldn't open auxiliary file chapter5.aux
---line 38 of file ./output/thesis.aux
 : \@input{chapter5.aux
 :                     }
I'm skipping whatever remains of this command
I couldn't open auxiliary file chapter6.aux
---line 39 of file ./output/thesis.aux
 : \@input{chapter6.aux
 :                     }
I'm skipping whatever remains of this command
The style file: IEEEtranN.bst
I couldn't open auxiliary file reference.aux
---line 41 of file ./output/thesis.aux
 : \@input{reference.aux
 :                      }
I'm skipping whatever remains of this command
I couldn't open auxiliary file publication.aux
---line 42 of file ./output/thesis.aux
 : \@input{publication.aux
 :                        }
I'm skipping whatever remains of this command
I couldn't open auxiliary file appendix1.aux
---line 45 of file ./output/thesis.aux
 : \@input{appendix1.aux
 :                      }
I'm skipping whatever remains of this command
I found no \citation commands---while reading file ./output/thesis.aux
I found no \bibdata command---while reading file ./output/thesis.aux
-- IEEEtranN.bst version 1.14 (2015/08/26) by Michael Shell.
-- http://www.michaelshell.org/tex/ieeetran/bibtex/
-- See the "IEEEtran_bst_HOWTO.pdf" manual for usage information.
** Natbib version - not for normal IEEE work.

**Comment by fcyu** [comment]
Not sure why you want to use this template for IEEE. It is for HKUST PhD or MPhil thesis.

**Comment by xiaoxstz** [comment]
It is not set by myself. I just download it and compiled
